services:
  - type: web
    name: viral-atolyesi-server
    env: node
    buildCommand: "npm install && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && chmod a+rx /usr/local/bin/yt-dlp"
    startCommand: "node server.js"
